name: William Huster
description: Entrepreneur. Small time CTO. Some kind of artist. Co-Founder and CTO at ThinkNimble.
author: William Huster
author_email: whusterj@gmail.com
category_dir: /
url: https://williamhuster.com

# Custom tag for default site image
# Post pages will typically override this with a "featured" image.
image: /static/images/facebook-image.jpg

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl:

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: /:title/

# How many articles do you wish to appear on the front page:
plugins: [jekyll-paginate]
paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md]

# Photos Collection
collections:
  photos:
    output: true
